edit pipeline

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -32,21 +32,26 @@ jobs:
           python -m venv exvenv
           python ./tests/test_hello.py
 
-      - name: Send Slack notification on success
-        if: ${{ success() }}
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-          MESSAGE: "Test cases succeeded on main branch!"
+      - name: Test
         run: |
-          curl -X POST -H 'Content-type: application/json' --data "{'text':'${MESSAGE}'}" $SLACK_WEBHOOK_URL
+          source venv/bin/activate
+          if python ./tests/test_hello.py | grep -q "OK"; then
+            echo "::set-output name=test_result::success"
+          else
+            echo "::set-output name=test_result::failure"
+            exit 1
+          fi
 
-      - name: Send Slack notification on failure
-        if: ${{ failure() }}
+      - name: Notify on Slack
+        uses: rtCamp/action-slack-notify@v2
+        if: always()
         env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-          MESSAGE: "Test cases failed on main branch!"
-        run: |
-          curl -X POST -H 'Content-type: application/json' --data "{'text':'${MESSAGE}'}" $SLACK_WEBHOOK_URL
+          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
+          SLACK_CHANNEL: "#botit-app"
+          SLACK_USERNAME: GitHub Actions
+        with:
+          args: |
+            Test result: ${{ steps.build.outputs.test_result }}
 
 
   # build_and_Push:
